---
title: 'Lecture 5 Lab: Interpretation of OLS'
output: pdf_document
date: "2023-11-20"
---

# Lecture 5 Lab: Interpretation of OLS

Read in the following variables from the 2018 Full Year Consolidated File (HC-209): DVTEXP18, RACEV1X, AGELAST, EDUCYR, SEX, INSCOV, and RTHLTH53. DVTEXP18 is dental care expenditures for 2018. INSCOV is a 3-category variable summarizing the sources of health insurance for respondents. RTHLTH53 is self-reported physical health with a 5-category Likert response scale. 


1.	Get to know your data. Drop observations with <=0 years of education and with missing/invalid responses to RTHLTH53. Describe the variables of interest (i.e., find descriptive statistics). 
2.	We are interested in racial disparities in dental care expenditures. Summarize dental expenditures by race categories in RACEV1X.
3.	Create a bar graph showing the ratio of mean dental expenditures for each race category in RACEV1X relative to White. For example, if mean dental expenditures for White people = $150 and mean dental expenditures for Black people = $100, the Black/White ratio would = 0.67. 
4.	Unadjusted means approach: Using t-tests, test for differences in mean dental expenditures between each race category in RACEV1X and White. Interpret any statistically significant differences. 
5.	Residual direct effect: Regression DVTEXP18 on RACEV1X, AGELAST, EDUCYR, SEX, INSCOV, and RTHLTH53 using White as the reference category for RACEV1X. Interpret any statistically significant differences in the RACEV1X categories. Be precise in your language. 
6.	IOM approach: Which variables would you include in the “Clinical Appropriateness and Need” category? Which variables would you include in the “Operation of health care systems and legal and regulatory environment” category? NOTE: We do not have measures of patient preferences.
7.	Generate predicted dental expenditures for the average White person.
8.	For each other race category in RACEV1X, generate predicted dental expenditures for the average person but use the White averages for Clinical Appropriateness and Need variables for every racial group. 
9.	Compare differences in predictions between race categories and White using the IOM approach vs the residual direct effect approach. Which approach generates larger disparities? For which racial groups? 
